version: "3.9"
services:


  redis:
    image: redis:7.0.0-alpine
    container_name: climafetch-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - climafetch-redis:/data
    env_file:
      - .env
    networks:
      - climafetch

volumes:
  climafetch-redis:

networks:
  climafetch:
    driver: bridge
